### ISSUE TITLE
evaluation de novo performance

### ISSUE THREAD

**Issue by yafeng** [lkytal/PepNet#6]
Hi, i was trying to follow the tutorial, but i couldn't find the python script "evaluation.py"
`python evaluation.py --mgf example.mgf --novorst example_prediction.tsv`
Can you tell me where i can download this file?Thanks!

Yafeng

**Comment by lkytal** [comment]
Hi, we have added the "evaluation.py" for a simple evaluation. The result TSV file should have ground truth peptide as the "Title" columns (e.g. when you run `denovo.py` over an MGF that uses truth peptide as the "Title" field)
